import type { Cardinality, EntityType, EnumName, Unit, ValueKind } from "./enums.js";

// The predicate registry. Unknown predicates are rejected by validation.
// docs/ontology.md is the human-readable mirror of this file; keep them in sync.

export interface PredicateDefinition {
  /** Entity types that may be the subject of this claim. */
  subject_types: readonly EntityType[];
  /** Which value column the claim uses. ENTITY claims are relationships. */
  value_kind: ValueKind;
  /** For ENTITY claims: allowed entity types of the object. */
  object_types?: readonly EntityType[];
  /** For NUMBER claims: the canonical unit. Also the unit of `measure` on ENTITY claims. */
  unit?: Unit;
  /** For ENUM claims: which enum the value must belong to. */
  enum_name?: EnumName;
  /** ONE = at most one open APPROVED claim per subject (per stack layer if applicable). */
  cardinality: Cardinality;
  /** True for USES_PRODUCT / USES_TECHNOLOGY: the claim carries a stack_layer. */
  is_stack_membership: boolean;
  /** Whether the claim may (or must) carry a stack_layer. */
  stack_layer: "REQUIRED" | "FORBIDDEN";
  /** For ENTITY claims that also carry a number (SCORES_ON): value_number + unit are allowed. */
  measure?: boolean;
  /** Plain-words label used when rendering the claim as a sentence. */
  label: string;
  description: string;
}

const ORG = ["ORGANIZATION"] as const;
const PRODUCTS = ["COMPONENT_PRODUCT", "SOFTWARE_PRODUCT", "MODEL"] as const;

export const PREDICATES = {
  // ---- Organization ---------------------------------------------------
  BUILDS: {
    subject_types: ORG,
    value_kind: "ENTITY",
    object_types: ["ROBOT"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "builds",
    description: "Organization is the OEM of a robot.",
  },
  DEVELOPS: {
    subject_types: ORG,
    value_kind: "ENTITY",
    object_types: ["MODEL", "SOFTWARE_PRODUCT"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "develops",
    description: "Organization develops a model or software product.",
  },
  PROVIDES: {
    subject_types: ORG,
    value_kind: "ENTITY",
    object_types: ["COMPONENT_PRODUCT", "SOFTWARE_PRODUCT"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "provides",
    description: "Organization supplies a component or software product (supplier role).",
  },
  TARGETS_MARKET: {
    subject_types: ["ORGANIZATION", "ROBOT"],
    value_kind: "ENTITY",
    object_types: ["MARKET"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "targets market",
    description: "Organization or robot is positioned for a market (sector or domain).",
  },
  TARGETS_TASK: {
    subject_types: ["ORGANIZATION", "ROBOT"],
    value_kind: "ENTITY",
    object_types: ["TASK"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "targets task",
    description: "Organization or robot is positioned for a task. Vendors of a task derive from this.",
  },
  PARTNERS_WITH: {
    subject_types: ORG,
    value_kind: "ENTITY",
    object_types: ["ORGANIZATION"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "partners with",
    description: "Announced partnership between two organizations.",
  },
  ACQUIRED: {
    subject_types: ORG,
    value_kind: "ENTITY",
    object_types: ["ORGANIZATION"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "acquired",
    description: "Subject acquired the object organization.",
  },
  PUBLISHES: {
    subject_types: ORG,
    value_kind: "ENTITY",
    object_types: ["PAPER"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "publishes",
    description: "Organization authored a paper (research-institution role).",
  },
  HQ_AT: {
    subject_types: ORG,
    value_kind: "ENTITY",
    object_types: ["PLACE"],
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "is headquartered at",
    description: "Headquarters location.",
  },
  RND_AT: {
    subject_types: ORG,
    value_kind: "ENTITY",
    object_types: ["PLACE"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "does R&D at",
    description: "Research and development site.",
  },
  MANUFACTURES_AT: {
    subject_types: ORG,
    value_kind: "ENTITY",
    object_types: ["PLACE"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "manufactures at",
    description: "Manufacturing site.",
  },
  FUNDED: {
    subject_types: ORG,
    value_kind: "NUMBER",
    unit: "USD",
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "raised",
    description: "Funding event. valid_from is the announcement date; value is USD raised.",
  },
  FOUNDED_ON: {
    subject_types: ORG,
    value_kind: "DATE",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "was founded on",
    description: "Founding date (year precision is fine: use YYYY-01-01 and is_approximate is implied by the source).",
  },

  // ---- Robot ------------------------------------------------------------
  USES_PRODUCT: {
    subject_types: ["ROBOT"],
    value_kind: "ENTITY",
    object_types: ["COMPONENT_PRODUCT", "SOFTWARE_PRODUCT"],
    cardinality: "MANY",
    is_stack_membership: true,
    stack_layer: "REQUIRED",
    label: "uses",
    description: "Stack membership: robot integrates a specific product at a stack layer.",
  },
  USES_TECHNOLOGY: {
    subject_types: ["ROBOT"],
    value_kind: "ENTITY",
    object_types: ["TECHNOLOGY"],
    cardinality: "MANY",
    is_stack_membership: true,
    stack_layer: "REQUIRED",
    label: "uses",
    description: "Stack membership: robot uses a technology class at a stack layer.",
  },
  HAS_ARCHITECTURE_NOTE: {
    subject_types: ["ROBOT"],
    value_kind: "TEXT",
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "REQUIRED",
    label: "architecture note",
    description: "One-paragraph known architecture for a stack layer; shown in the MRI layer focus.",
  },
  COMPETES_WITH: {
    subject_types: ["ROBOT", "COMPONENT_PRODUCT", "SOFTWARE_PRODUCT", "MODEL", "TECHNOLOGY", "ORGANIZATION"],
    value_kind: "ENTITY",
    object_types: ["ROBOT", "COMPONENT_PRODUCT", "SOFTWARE_PRODUCT", "MODEL", "TECHNOLOGY", "ORGANIZATION"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "competes with",
    description: "Peer relationship. Subject and object must share an entity type (validated).",
  },
  MEMBER_OF_FAMILY: {
    subject_types: ["ROBOT"],
    value_kind: "ENTITY",
    object_types: ["ROBOT_FAMILY"],
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "is a member of",
    description: "Robot belongs to a robot family (generations and timelines hang off this).",
  },
  SUCCEEDS: {
    subject_types: ["ROBOT"],
    value_kind: "ENTITY",
    object_types: ["ROBOT"],
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "succeeds",
    description: "Generation link: subject is the successor of the object robot.",
  },
  CONTROLLED_BY: {
    subject_types: ["ROBOT"],
    value_kind: "ENTITY",
    object_types: ["MODEL"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "is controlled by",
    description: "Robot is driven by a named model (policy / VLA).",
  },
  SCORES_ON: {
    subject_types: ["ROBOT", "MODEL"],
    value_kind: "ENTITY",
    object_types: ["BENCHMARK"],
    unit: "score",
    measure: true,
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "scores on",
    description: "Benchmark result: object is the benchmark, value_number + unit carry the score.",
  },
  HAS_HEIGHT: {
    subject_types: ["ROBOT"],
    value_kind: "NUMBER",
    unit: "m",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "height",
    description: "Standing height in metres.",
  },
  HAS_MASS: {
    subject_types: ["ROBOT"],
    value_kind: "NUMBER",
    unit: "kg",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "mass",
    description: "Mass in kilograms (without payload).",
  },
  HAS_PAYLOAD: {
    subject_types: ["ROBOT"],
    value_kind: "NUMBER",
    unit: "kg",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "payload",
    description: "Rated payload in kilograms.",
  },
  HAS_DOF: {
    subject_types: ["ROBOT"],
    value_kind: "NUMBER",
    unit: "count",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "degrees of freedom",
    description: "Total actuated degrees of freedom.",
  },
  HAS_RUNTIME: {
    subject_types: ["ROBOT"],
    value_kind: "NUMBER",
    unit: "s",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "runtime",
    description: "Battery runtime (or flight time) in seconds.",
  },
  HAS_REACH: {
    subject_types: ["ROBOT"],
    value_kind: "NUMBER",
    unit: "m",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "reach",
    description: "Arm reach in metres.",
  },
  HAS_LIST_PRICE: {
    subject_types: ["ROBOT", "COMPONENT_PRODUCT", "SOFTWARE_PRODUCT"],
    value_kind: "NUMBER",
    unit: "USD",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "list price",
    description: "Published base list price in USD.",
  },
  HAS_COMMERCIAL_STAGE: {
    subject_types: ["ROBOT"],
    value_kind: "ENUM",
    enum_name: "CommercialStage",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "commercial stage",
    description: "Can you buy and deploy it today? Cached to entities.commercial_stage.",
  },
  HAS_EMBODIMENT: {
    subject_types: ["ROBOT"],
    value_kind: "ENUM",
    enum_name: "Embodiment",
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "embodiment",
    description: "Embodiment class. entities.primary_embodiment is the typed-core mirror of the primary one.",
  },
  ANNOUNCED_ON: {
    subject_types: ["ROBOT", "MODEL", "COMPONENT_PRODUCT", "SOFTWARE_PRODUCT"],
    value_kind: "DATE",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "was announced on",
    description: "Public announcement or release date.",
  },

  // ---- Deployment -----------------------------------------------------
  USES_ROBOT: {
    subject_types: ["DEPLOYMENT"],
    value_kind: "ENTITY",
    object_types: ["ROBOT"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "uses robot",
    description: "Robot(s) deployed.",
  },
  DEPLOYED_BY: {
    subject_types: ["DEPLOYMENT"],
    value_kind: "ENTITY",
    object_types: ["ORGANIZATION"],
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "is deployed by",
    description: "The customer organization (customer role derives from this).",
  },
  OPERATED_BY: {
    subject_types: ["DEPLOYMENT"],
    value_kind: "ENTITY",
    object_types: ["ORGANIZATION"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "is operated by",
    description: "Vendor or integrator operating the deployment.",
  },
  OCCURS_AT: {
    subject_types: ["DEPLOYMENT"],
    value_kind: "ENTITY",
    object_types: ["PLACE"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "occurs at",
    description: "Deployment site.",
  },
  SERVES_TASK: {
    subject_types: ["DEPLOYMENT"],
    value_kind: "ENTITY",
    object_types: ["TASK"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "serves task",
    description: "Task the deployment performs. Deployment counts on tasks derive from this.",
  },
  HAS_SCALE: {
    subject_types: ["DEPLOYMENT"],
    value_kind: "NUMBER",
    unit: "units",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "scale",
    description: "Number of robots (units) in the deployment.",
  },
  BEGAN: {
    subject_types: ["DEPLOYMENT"],
    value_kind: "DATE",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "began",
    description: "Deployment start date; the claim's valid_from carries the same date.",
  },

  // ---- Product / technology ------------------------------------------
  IS_INSTANCE_OF: {
    subject_types: PRODUCTS,
    value_kind: "ENTITY",
    object_types: ["TECHNOLOGY"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "is an instance of",
    description: "Product belongs to a technology class.",
  },
  MADE_BY: {
    subject_types: PRODUCTS,
    value_kind: "ENTITY",
    object_types: ["ORGANIZATION"],
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "is made by",
    description: "Maker of a product or model.",
  },

  // ---- Model / paper ----------------------------------------------------
  INTRODUCED_BY: {
    subject_types: ["MODEL"],
    value_kind: "ENTITY",
    object_types: ["PAPER"],
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "was introduced by",
    description: "Paper that introduced the model.",
  },
  TRAINED_ON: {
    subject_types: ["MODEL"],
    value_kind: "ENTITY",
    object_types: ["DATASET"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "was trained on",
    description: "Training dataset.",
  },

  // ---- Market / task ----------------------------------------------------
  CHILD_OF: {
    subject_types: ["MARKET"],
    value_kind: "ENTITY",
    object_types: ["MARKET"],
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "is a domain of",
    description: "Domain market → sector market.",
  },
  BELONGS_TO_MARKET: {
    subject_types: ["TASK"],
    value_kind: "ENTITY",
    object_types: ["MARKET"],
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "belongs to",
    description: "Task → domain market.",
  },
  HAS_INCUMBENT_PROCESS: {
    subject_types: ["TASK"],
    value_kind: "TEXT",
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "incumbent process",
    description: "How the task is done today without robots.",
  },
  HAS_MATURITY: {
    subject_types: ["TASK", "APPROACH"],
    value_kind: "ENUM",
    enum_name: "Maturity",
    cardinality: "ONE",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "maturity",
    description: "Analyst maturity assessment. Cached to entities.maturity. Evidence is always ANALYST.",
  },
  HAS_APPROACH: {
    subject_types: ["TASK"],
    value_kind: "ENTITY",
    object_types: ["APPROACH"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "has approach",
    description: "A competing robotics approach to the task.",
  },
  USES_EMBODIMENT: {
    subject_types: ["APPROACH"],
    value_kind: "ENUM",
    enum_name: "Embodiment",
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "uses embodiment",
    description: "Embodiment class an approach relies on.",
  },
  HAS_EXAMPLE_VENDOR: {
    subject_types: ["APPROACH"],
    value_kind: "ENTITY",
    object_types: ["ORGANIZATION"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "example vendor",
    description: "Organization pursuing this approach.",
  },
  REQUIRES_TECHNOLOGY: {
    subject_types: ["TASK", "APPROACH"],
    value_kind: "ENTITY",
    object_types: ["TECHNOLOGY"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "requires",
    description: "Technology class the task or approach depends on.",
  },
  HAS_TECHNICAL_REQUIREMENT: {
    subject_types: ["TASK", "APPROACH"],
    value_kind: "TEXT",
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "technical requirement",
    description: "A capability the task demands, in plain words (e.g. contact stability in wind).",
  },
  HAS_ADOPTION_BLOCKER: {
    subject_types: ["TASK"],
    value_kind: "TEXT",
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "adoption blocker",
    description: "Analyst-identified barrier to adoption. Evidence is ANALYST.",
  },
  HAS_CUSTOMER_TYPE: {
    subject_types: ["TASK"],
    value_kind: "TEXT",
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "customer type",
    description: "Who buys robots for this task.",
  },
  ADJACENT_TO: {
    subject_types: ["TASK"],
    value_kind: "ENTITY",
    object_types: ["TASK"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "is adjacent to",
    description: "Neighbouring task (shared sites, customers, or hardware).",
  },
  HAS_ECONOMICS_NOTE: {
    subject_types: ["TASK"],
    value_kind: "TEXT",
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "economics",
    description: "Evidence-classed note on unit economics; rendered only when present.",
  },

  // ---- Geography (any entity) ------------------------------------------
  LOCATED_AT: {
    subject_types: ["ORGANIZATION", "ROBOT", "DEPLOYMENT", "PAPER", "BENCHMARK"],
    value_kind: "ENTITY",
    object_types: ["PLACE"],
    cardinality: "MANY",
    is_stack_membership: false,
    stack_layer: "FORBIDDEN",
    label: "is located at",
    description: "Generic location link when none of HQ/RND/MANUFACTURES/OCCURS applies.",
  },
} as const satisfies Record<string, PredicateDefinition>;

export type Predicate = keyof typeof PREDICATES;
export const PREDICATE_NAMES = Object.keys(PREDICATES) as Predicate[];

export function isPredicate(value: string): value is Predicate {
  return Object.prototype.hasOwnProperty.call(PREDICATES, value);
}

export function predicateDefinition(predicate: Predicate): PredicateDefinition {
  return PREDICATES[predicate];
}

export const STACK_MEMBERSHIP_PREDICATES = PREDICATE_NAMES.filter((p) => PREDICATES[p].is_stack_membership);
export const RELATIONSHIP_PREDICATES = PREDICATE_NAMES.filter((p) => PREDICATES[p].value_kind === "ENTITY");
