/** Read handlers shared by HTTP and the fixture generator.  They deliberately use a
 * small in-memory read model: the contract is explicit, deterministic, and easy to
 * replace with tuned SQL when traffic warrants it. */
import {
  assessments, changeEvents, claimDependencies, claims, embodimentLayerLabels, entities, entityAliases, evidence, places, sources,
  type Db,
} from "@ri/db";
import {
  AtlasQuery, AtlasResponse, ClaimEvidenceParams, ClaimEvidenceResponse, CompareBody, CompareResponse, EntityParams, EntityQuery,
  EntityResponse, ExploreQuery, ExploreResponse, MarketParams, MarketQuery, MarketResponse, StackParams, StackQuery, StackResponse,
  RobotsQuery, RobotsResponse, SearchQuery, SearchResponse, TaskParams, TaskQuery, TaskResponse, UpdatesQuery, UpdatesResponse,
  type AssessmentView, type ClaimValue, type DiscoveryFilters, type EntityChip,
} from "@ri/api-contracts";
import { CANONICAL_LAYERS, PREDICATES, type Embodiment } from "@ri/domain";
import type { ApiContext } from "./context.js";
import { maxConfidence, NOT_AVAILABLE, summarize } from "./lib/evidence.js";
import { predicateLabel, rowSentence, rowValue, type ClaimRow, type EntityRow } from "./lib/value.js";

type Snapshot = Awaited<ReturnType<typeof load>>;
const chip = (e: EntityRow): EntityChip => ({ id: e.id, slug: e.slug, entity_type: e.entityType, name: e.name, primary_embodiment: e.primaryEmbodiment });
const nameSort = <T extends { name: string; slug: string }>(a: T, b: T) => a.name.localeCompare(b.name) || a.slug.localeCompare(b.slug);
// node-postgres returns timestamp columns as PostgreSQL strings; contracts use RFC 3339.
const iso = (value: string | null): string | null => value === null ? null : new Date(value).toISOString();

async function load(ctx: ApiContext) {
  const [es, cs, evs, ss, aa, ps, aliases, labels, events, deps] = await Promise.all([
    ctx.db.select().from(entities), ctx.db.select().from(claims), ctx.db.select().from(evidence), ctx.db.select().from(sources),
    ctx.db.select().from(assessments), ctx.db.select().from(places), ctx.db.select().from(entityAliases), ctx.db.select().from(embodimentLayerLabels),
    ctx.db.select().from(changeEvents), ctx.db.select().from(claimDependencies),
  ]);
  const entity = new Map(es.map((x) => [x.id, x]));
  const claim = new Map(cs.map((x) => [x.id, x]));
  const bySubject = new Map<string, ClaimRow[]>(), byObject = new Map<string, ClaimRow[]>(), evByClaim = new Map<string, typeof evs>();
  for (const c of cs) { (bySubject.get(c.subjectEntityId) ?? (bySubject.set(c.subjectEntityId, []), bySubject.get(c.subjectEntityId)!)).push(c); if (c.objectEntityId) (byObject.get(c.objectEntityId) ?? (byObject.set(c.objectEntityId, []), byObject.get(c.objectEntityId)!)).push(c); }
  for (const e of evs) (evByClaim.get(e.claimId) ?? (evByClaim.set(e.claimId, []), evByClaim.get(e.claimId)!)).push(e);
  const assessment = new Map(aa.map((x) => [x.evidenceId, x]));
  const source = new Map(ss.map((x) => [x.id, x]));
  const place = new Map(ps.map((x) => [x.entityId, x]));
  const aliasesByEntity = new Map<string, string[]>(); for (const a of aliases) (aliasesByEntity.get(a.entityId) ?? (aliasesByEntity.set(a.entityId, []), aliasesByEntity.get(a.entityId)!)).push(a.alias);
  const label = new Map(labels.map((x) => [`${x.embodiment}:${x.layer}`, x]));
  const depByClaim = new Map<string, string[]>(); for (const d of deps) (depByClaim.get(d.derivedClaimId) ?? (depByClaim.set(d.derivedClaimId, []), depByClaim.get(d.derivedClaimId)!)).push(d.inputClaimId);
  const visible = (c: ClaimRow) => ctx.asOf ? (c.status === "APPROVED" || c.status === "SUPERSEDED") && c.validFrom <= ctx.asOf && (c.validTo === null || c.validTo > ctx.asOf) : c.status === "APPROVED" && c.validTo === null;
  return { es, cs, evs, source, entity, claim, bySubject, byObject, evByClaim, assessment, place, aliasesByEntity, label, events, depByClaim, visible, asOf: ctx.asOf };
}

function assessmentView(s: Snapshot, evidenceId: string): AssessmentView | null {
  const a = s.assessment.get(evidenceId); if (!a) return null;
  return { author: a.author, rationale: a.rationale, advance_criteria: a.advanceCriteria, regress_criteria: a.regressCriteria,
    evidence_considered: a.evidenceConsidered.flatMap((id) => { const c = s.claim.get(id), e = c && s.entity.get(c.subjectEntityId); return c && e ? [{ claim_id: id, sentence: rowSentence(c, e, c.objectEntityId ? s.entity.get(c.objectEntityId) : null) }] : []; }), reviewed_at: iso(a.reviewedAt)!, notes: a.notes };
}
function value(s: Snapshot, c: ClaimRow): ClaimValue { return rowValue(c, c.objectEntityId ? s.entity.get(c.objectEntityId) : null); }
function summary(s: Snapshot, c: ClaimRow) { return summarize(s.evByClaim.get(c.id) ?? []); }
function claimView(s: Snapshot, c: ClaimRow) { return { claim_id: c.id, predicate: c.predicate, value: value(s, c), stack_layer: c.stackLayer, valid_from: c.validFrom, valid_to: c.validTo, observed_at: iso(c.observedAt)!, last_verified_at: iso(c.lastVerifiedAt)!, has_evidence: (s.evByClaim.get(c.id)?.length ?? 0) > 0, evidence_summary: summary(s, c) }; }
function textItem(s: Snapshot, c: ClaimRow) { const analyst = (s.evByClaim.get(c.id) ?? []).find((x) => x.evidenceClass === "ANALYST"); return { claim_id: c.id, text: c.valueText!, evidence_summary: summary(s, c), assessment: analyst ? assessmentView(s, analyst.id) : null }; }
function publicSubject(s: Snapshot, id: string) { return (s.bySubject.get(id) ?? []).filter(s.visible); }
function publicObject(s: Snapshot, id: string) { return (s.byObject.get(id) ?? []).filter(s.visible); }
function getEntity(s: Snapshot, slug: string) { const e = s.es.find((x) => x.slug === slug); if (!e) throw new Error(`entity not found: ${slug}`); return e; }
function unique(items: EntityChip[]) { const seen = new Set<string>(); return items.filter((x) => !seen.has(x.id) && !!seen.add(x.id)).sort(nameSort); }
function matchesFilters(e: EntityRow, filters: DiscoveryFilters) {
  return (!filters.entity_type || e.entityType === filters.entity_type)
    && (!filters.embodiment || e.primaryEmbodiment === filters.embodiment)
    && (!filters.commercial_stage || e.commercialStage === filters.commercial_stage)
    && (!filters.maturity || e.maturity === filters.maturity)
    && (!filters.country_code || e.countryCode === filters.country_code);
}

export async function entityHandler(ctx: ApiContext, input: unknown) {
  const p = EntityParams.parse((input as { params?: unknown })?.params ?? input), q = EntityQuery.parse((input as { query?: unknown })?.query ?? {}); const s = await load({ ...ctx, asOf: q.as_of ?? ctx.asOf }); const e = getEntity(s, p.slug);
  const own = publicSubject(s, e.id), inbound = publicObject(s, e.id);
  const scalar = own.filter((c) => c.objectEntityId === null).reduce<Map<string, ClaimRow[]>>((m,c) => (m.set(c.predicate,[...(m.get(c.predicate)??[]),c]),m),new Map());
  const rel = own.filter((c) => c.objectEntityId !== null).reduce<Map<string, ClaimRow[]>>((m,c) => (m.set(c.predicate,[...(m.get(c.predicate)??[]),c]),m),new Map());
  const inRel = inbound.reduce<Map<string, ClaimRow[]>>((m,c) => (m.set(c.predicate,[...(m.get(c.predicate)??[]),c]),m),new Map());
  const related = [...rel.values(), ...inRel.values()].flat().flatMap((c) => [c.objectEntityId === e.id ? s.entity.get(c.subjectEntityId) : s.entity.get(c.objectEntityId!)]).filter((x): x is EntityRow => !!x);
  const classes: Record<string, number> = { PRIMARY: 0, THIRD_PARTY: 0, ACADEMIC: 0, DERIVED: 0, ANALYST: 0 };
  for (const c of own) for (const ev of s.evByClaim.get(c.id) ?? []) classes[ev.evidenceClass] = (classes[ev.evidenceClass] ?? 0) + 1;
  const lateral = { categories: [] as EntityChip[], company: [] as EntityChip[], technologies: [] as EntityChip[], markets: [] as EntityChip[], places: [] as EntityChip[], peers: [] as EntityChip[] };
  for (const c of [...own, ...inbound]) { const other = c.subjectEntityId === e.id ? c.objectEntityId && s.entity.get(c.objectEntityId) : s.entity.get(c.subjectEntityId); if (!other) continue; const x = chip(other); if (["TECHNOLOGY"].includes(other.entityType)) lateral.technologies.push(x); else if (other.entityType === "MARKET") lateral.markets.push(x); else if (other.entityType === "PLACE") lateral.places.push(x); else if (other.entityType === "ORGANIZATION") lateral.company.push(x); else if (c.predicate === "COMPETES_WITH") lateral.peers.push(x); else if (["ROBOT_FAMILY", "APPROACH"].includes(other.entityType)) lateral.categories.push(x); }
  const l: Record<string, EntityChip[]> = {};
  for (const [key, chips] of Object.entries(lateral)) { const values = unique(chips); if (values.length) l[key] = values; }
  const response = { entity: { id:e.id, slug:e.slug, entity_type:e.entityType, name:e.name, short_description:e.shortDescription, primary_embodiment:e.primaryEmbodiment, country_code:e.countryCode, aliases:s.aliasesByEntity.get(e.id) ?? [], created_at:iso(e.createdAt)!, updated_at:iso(e.updatedAt)! }, cached: { commercial_stage:e.commercialStage, height_m:e.heightM, mass_kg:e.massKg, payload_kg:e.payloadKg, list_price_usd:e.listPriceUsd, maturity:e.maturity }, place: s.place.get(e.id) ? { admin_region:s.place.get(e.id)!.adminRegion, city:s.place.get(e.id)!.city, lat:s.place.get(e.id)!.lat, lng:s.place.get(e.id)!.lng, cluster_label:s.place.get(e.id)!.clusterLabel } : null,
    claims:[...scalar].map(([predicate,rows])=>({predicate,label:predicateLabel(predicate),claims:rows.map(c=>claimView(s,c))})), relationships:[...rel].map(([predicate,rows])=>({predicate,label:predicateLabel(predicate),items:rows.flatMap(c=>{const target=s.entity.get(c.objectEntityId!);return target?[{claim_id:c.id,target:chip(target),stack_layer:c.stackLayer,valid_from:c.validFrom,has_evidence:(s.evByClaim.get(c.id)?.length??0)>0,evidence_summary:summary(s,c)}]:[]})})), inbound_relationships:[...inRel].map(([predicate,rows])=>({predicate,label:predicateLabel(predicate),items:rows.flatMap(c=>{const source=s.entity.get(c.subjectEntityId);return source?[{claim_id:c.id,source:chip(source),stack_layer:c.stackLayer,valid_from:c.validFrom,has_evidence:(s.evByClaim.get(c.id)?.length??0)>0,evidence_summary:summary(s,c)}]:[]})})), lateral_links:l,
    intelligence:{evidence_summary:{by_class:classes,claim_count:own.length,claims_without_evidence:own.filter(c=>(s.evByClaim.get(c.id)?.length??0)===0).length},last_verified_at:iso(own.map(c=>c.lastVerifiedAt).sort().at(-1)??null),recent_change_count:s.events.filter(x=>x.entityId===e.id).length,deployment_count:publicObject(s,e.id).filter(c=>c.predicate==="USES_ROBOT").length,related_count:new Set(related.map(x=>x.id)).size},as_of:s.asOf };
  return EntityResponse.parse(response);
}

export async function stackHandler(ctx: ApiContext, input: unknown) {
  const p=StackParams.parse((input as {params?:unknown})?.params??input),q=StackQuery.parse((input as {query?:unknown})?.query??{}); const s=await load({...ctx,asOf:q.as_of??ctx.asOf}); const robot=getEntity(s,p.slug); if(robot.entityType!=="ROBOT"||!robot.primaryEmbodiment) throw new Error(`${p.slug} is not a robot with an embodiment`);
  const own=publicSubject(s,robot.id), stack=own.filter(c=>["USES_PRODUCT","USES_TECHNOLOGY"].includes(c.predicate)); const item=(c:ClaimRow)=>{const e=s.entity.get(c.objectEntityId!);return e?{entity:chip(e),kind:c.predicate==="USES_PRODUCT"?"product":"technology",claim_id:c.id,evidence_summary:summary(s,c)}:null};
  const layers=CANONICAL_LAYERS.flatMap(canonical=>{const l=s.label.get(`${robot.primaryEmbodiment}:${canonical}`);if(!l?.applies)return[];const note=own.find(c=>c.predicate==="HAS_ARCHITECTURE_NOTE"&&c.stackLayer===canonical);return[{canonical,label:l.label,applies:true as const,items:stack.filter(c=>c.stackLayer===canonical).flatMap(c=>{const x=item(c);return x?[x]:[]}),...(note?{architecture_note:{claim_id:note.id,text:note.valueText!,evidence_summary:summary(s,note)}}:{})}]});
  return StackResponse.parse({robot:chip(robot),embodiment:robot.primaryEmbodiment,layers,safety:stack.filter(c=>c.stackLayer==="SAFETY").flatMap(c=>{const x=item(c);return x?[x]:[]}),as_of:s.asOf});
}

function marketPath(s: Snapshot, task: EntityRow) { const first=publicSubject(s,task.id).find(c=>c.predicate==="BELONGS_TO_MARKET"); const out:EntityRow[]=[]; let current=first?.objectEntityId?s.entity.get(first.objectEntityId):undefined; while(current){out.unshift(current); const parent=publicSubject(s,current.id).find(c=>c.predicate==="CHILD_OF");current=parent?.objectEntityId?s.entity.get(parent.objectEntityId):undefined;} return out.map(chip); }
function marketAncestors(s: Snapshot, market: EntityRow) { const out: EntityRow[] = []; let current: EntityRow | undefined = market; while (current) { const parent: ClaimRow | undefined = publicSubject(s, current.id).find((c) => c.predicate === "CHILD_OF"); current = parent?.objectEntityId ? s.entity.get(parent.objectEntityId) : undefined; if (current) out.unshift(current); } return out.map(chip); }
function maturity(s:Snapshot,e:EntityRow){const c=publicSubject(s,e.id).find(x=>x.predicate==="HAS_MATURITY");if(!c)return undefined; const ev=(s.evByClaim.get(c.id)??[]).find(x=>x.evidenceClass==="ANALYST");return{value:c.valueEnum!,claim_id:c.id,evidence_summary:summary(s,c),assessment:ev?assessmentView(s,ev.id):null};}

export async function taskHandler(ctx:ApiContext,input:unknown){const p=TaskParams.parse((input as {params?:unknown})?.params??input),q=TaskQuery.parse((input as {query?:unknown})?.query??{});const s=await load({...ctx,asOf:q.as_of??ctx.asOf});const task=getEntity(s,p.slug);if(task.entityType!=="TASK")throw new Error(`${p.slug} is not a task`);const own=publicSubject(s,task.id),of=(x:string)=>own.filter(c=>c.predicate===x), chips=(x:string)=>unique(of(x).flatMap(c=>{const e=c.objectEntityId&&s.entity.get(c.objectEntityId);return e?[chip(e)]:[]}));
 const approaches=of("HAS_APPROACH").flatMap(c=>{const a=c.objectEntityId&&s.entity.get(c.objectEntityId);if(!a)return[];const ac=publicSubject(s,a.id);return[{approach:chip(a),short_description:a.shortDescription,maturity:maturity(s,a),embodiments:ac.filter(x=>x.predicate==="USES_EMBODIMENT").map(x=>x.valueEnum as Embodiment),example_vendors:unique(ac.filter(x=>x.predicate==="HAS_EXAMPLE_VENDOR").flatMap(x=>{const e=x.objectEntityId&&s.entity.get(x.objectEntityId);return e?[chip(e)]:[]}))}]});
 const deployments=s.es.filter(e=>e.entityType==="DEPLOYMENT").flatMap(d=>{const cs=publicSubject(s,d.id);if(!cs.some(c=>c.predicate==="SERVES_TASK"&&c.objectEntityId===task.id))return[];const one=(p:string)=>{const c=cs.find(x=>x.predicate===p), e=c?.objectEntityId&&s.entity.get(c.objectEntityId);return e?chip(e):null};return[{deployment:chip(d),customer:one("DEPLOYED_BY"),operators:unique(cs.filter(c=>c.predicate==="OPERATED_BY").flatMap(c=>{const e=c.objectEntityId&&s.entity.get(c.objectEntityId);return e?[chip(e)]:[]})),robots:unique(cs.filter(c=>c.predicate==="USES_ROBOT").flatMap(c=>{const e=c.objectEntityId&&s.entity.get(c.objectEntityId);return e?[chip(e)]:[]})),places:unique(cs.filter(c=>c.predicate==="OCCURS_AT").flatMap(c=>{const e=c.objectEntityId&&s.entity.get(c.objectEntityId);return e?[chip(e)]:[]})),began:cs.find(c=>c.predicate==="BEGAN")?.valueDate??null,evidence_summary:summary(s,cs.find(c=>c.predicate==="SERVES_TASK")!)}]});
 const vendors=unique(s.es.filter(e=>e.entityType==="ORGANIZATION"&&publicSubject(s,e.id).some(c=>c.predicate==="TARGETS_TASK"&&c.objectEntityId===task.id)).map(chip)).map(organization=>({organization,via:"TARGETS_TASK" as const}));
 const response={task:chip(task),short_description:task.shortDescription,market_path:marketPath(s,task),...(maturity(s,task)?{maturity:maturity(s,task)}:{}),...(of("HAS_INCUMBENT_PROCESS").length?{incumbent_process:of("HAS_INCUMBENT_PROCESS").map(c=>textItem(s,c))}:{}),...(approaches.length?{approaches}:{}),...(chips("REQUIRES_TECHNOLOGY").length?{required_technologies:chips("REQUIRES_TECHNOLOGY")}:{}) ,...(of("HAS_TECHNICAL_REQUIREMENT").length?{technical_requirements:of("HAS_TECHNICAL_REQUIREMENT").map(c=>textItem(s,c))}:{}),...(vendors.length?{vendors}:{}),...(deployments.length?{deployments}:{}),...(of("HAS_CUSTOMER_TYPE").length?{customer_types:of("HAS_CUSTOMER_TYPE").map(c=>textItem(s,c))}:{}),...(of("HAS_ADOPTION_BLOCKER").length?{blockers:of("HAS_ADOPTION_BLOCKER").map(c=>textItem(s,c))}:{}),...(chips("ADJACENT_TO").length?{adjacent_tasks:chips("ADJACENT_TO")}:{}) ,...(of("HAS_ECONOMICS_NOTE").length?{economics_notes:of("HAS_ECONOMICS_NOTE").map(c=>textItem(s,c))}:{}),as_of:s.asOf};return TaskResponse.parse(response);}

export async function searchHandler(ctx:ApiContext,input:unknown){const query=SearchQuery.parse(input),{q,limit}=query;const s=await load(ctx),needle=q?.toLowerCase();const results=s.es.filter(e=>matchesFilters(e,query)).flatMap(e=>{const aliases=s.aliasesByEntity.get(e.id)??[];const field=!needle?"name":e.name.toLowerCase().includes(needle)?"name":aliases.some(a=>a.toLowerCase().includes(needle))?"alias":e.shortDescription?.toLowerCase().includes(needle)?"description":null;return field?[{chip:chip(e),entity_type:e.entityType,match_field:field,rank:needle?(field==="name"?3:field==="alias"?2:1):0}]:[]}).sort((a,b)=>b.rank-a.rank||nameSort(a.chip,b.chip)).slice(0,limit);return SearchResponse.parse({query:q??"",results});}

export async function robotsHandler(ctx:ApiContext,input:unknown){const q=RobotsQuery.parse(input);const s=await load({...ctx,asOf:q.as_of??ctx.asOf});const robots=s.es.filter(e=>e.entityType==="ROBOT"&&matchesFilters(e,q)).map(chip).sort(nameSort);return RobotsResponse.parse({robots,as_of:s.asOf});}

export async function exploreHandler(ctx:ApiContext,input:unknown){const q=ExploreQuery.parse(input);const s=await load({...ctx,asOf:q.as_of??ctx.asOf});const groups=new Map<string,Map<string,{label:string;items:{e:EntityRow;primary:boolean}[]}>>();const add=(region:string,regionLabel:string,district:string,districtLabel:string,e:EntityRow,primary=true)=>{if(!matchesFilters(e,q))return;const r=groups.get(region)??(groups.set(region,new Map()),groups.get(region)!);const d=r.get(district)??(r.set(district,{label:districtLabel,items:[]}),r.get(district)!);d.items.push({e,primary});};
 if(q.lens==="embodiment") for(const e of s.es.filter(e=>e.entityType==="ROBOT"&&e.primaryEmbodiment))add(e.primaryEmbodiment!,e.primaryEmbodiment!,e.primaryEmbodiment!,e.primaryEmbodiment!,e);
 else if(q.lens==="market") for(const t of s.es.filter(e=>e.entityType==="TASK")){const path=marketPath(s,t);for(const [i,m] of path.entries())add(path[0]?.slug??"other",path[0]?.name??"Other",m.slug,m.name,t,i===path.length-1);}
 else if(q.lens==="technology") for(const r of s.es.filter(e=>e.entityType==="ROBOT"))for(const c of publicSubject(s,r.id).filter(c=>c.predicate==="USES_TECHNOLOGY")){const t=c.objectEntityId&&s.entity.get(c.objectEntityId);if(t)add("technology","Technology",t.slug,t.name,r,true);}
 else if(q.lens==="geography") for(const e of s.es.filter(e=>e.countryCode))add(e.countryCode!,e.countryCode!,e.countryCode!,e.countryCode!,e);
 else for(const t of s.es.filter(e=>e.entityType==="TASK"&&maturity(s,e))) {const m=maturity(s,t)!;add(m.value,m.value,m.value,m.value,t);}
 const measure=(e:EntityRow)=>q.measure==="none"?null:q.measure==="robots"?(e.entityType==="ROBOT"?1:0):publicObject(s,e.id).filter(c=>c.predicate==="USES_ROBOT").length;
 const regions=[...groups].map(([id,districts])=>({id,label:[...districts.values()][0]?.items[0]?.e.countryCode??id,count:new Set([...districts.values()].flatMap(d=>d.items.map(x=>x.e.id))).size,districts:[...districts].map(([did,d])=>({id:did,label:d.label,count:new Set(d.items.map(x=>x.e.id)).size,entities:d.items.map(x=>({chip:chip(x.e),measure_value:measure(x.e),is_primary_membership:x.primary})).sort((a,b)=>nameSort(a.chip,b.chip))}))}));return ExploreResponse.parse({lens:q.lens,measure:q.measure,regions,as_of:s.asOf});}

export async function marketHandler(ctx:ApiContext,input:unknown){const p=MarketParams.parse((input as {params?:unknown})?.params??input),q=MarketQuery.parse((input as {query?:unknown})?.query??{});const s=await load({...ctx,asOf:q.as_of??ctx.asOf});const market=getEntity(s,p.slug);if(market.entityType!=="MARKET")throw new Error("not a market");const children=s.es.filter(e=>e.entityType==="MARKET"&&publicSubject(s,e.id).some(c=>c.predicate==="CHILD_OF"&&c.objectEntityId===market.id));const descendant=new Set([market.id,...children.map(c=>c.id)]);const taskEntities=s.es.filter(e=>e.entityType==="TASK"&&publicSubject(s,e.id).some(c=>c.predicate==="BELONGS_TO_MARKET"&&c.objectEntityId&&descendant.has(c.objectEntityId)));const path=marketAncestors(s,market);const board=taskEntities.map(t=>{const m=maturity(s,t),approach=publicSubject(s,t.id).find(c=>c.predicate==="HAS_APPROACH");const a=approach?.objectEntityId&&s.entity.get(approach.objectEntityId);const domain=marketPath(s,t).at(-1);return{task:chip(t),domain:domain??chip(market),maturity:m?.value??null,maturity_claim_id:m?.claim_id??null,dominant_approach:a?chip(a):null,vendor_count:s.es.filter(e=>e.entityType==="ORGANIZATION"&&publicSubject(s,e.id).some(c=>c.predicate==="TARGETS_TASK"&&c.objectEntityId===t.id)).length,deployment_count:s.es.filter(e=>e.entityType==="DEPLOYMENT"&&publicSubject(s,e.id).some(c=>c.predicate==="SERVES_TASK"&&c.objectEntityId===t.id)).length};});return MarketResponse.parse({market:chip(market),short_description:market.shortDescription,path,children:children.map(chip).sort(nameSort),board,as_of:s.asOf});}

export async function compareHandler(ctx:ApiContext,input:unknown){const q=CompareBody.parse(input),s=await load({...ctx,asOf:q.as_of??ctx.asOf}),cols=q.slugs.map(x=>getEntity(s,x));const all=new Map<string,ClaimRow[][]>();for(const [i,e] of cols.entries())for(const c of publicSubject(s,e.id)){if(c.predicate==="HAS_ARCHITECTURE_NOTE")continue;const key=`${c.stackLayer??attributeGroup(c.predicate)}:${c.predicate}`;const per=all.get(key)??Array.from({length:cols.length},()=>[] as ClaimRow[]);per[i]!.push(c);all.set(key,per);}const grouped=new Map<string,{predicate:string;label:string;cells:unknown[]}[]>();for(const [key,per] of all){if(per.filter(x=>x.length).length<2)continue;const [group,predicate]=key.split(":") as [string,string];const row={predicate,label:predicateLabel(predicate),cells:per.map(cs=>cs.length?{values:cs.map(c=>({claim_id:c.id,value:value(s,c),evidence_summary:summary(s,c)}))}:null)};(grouped.get(group)??(grouped.set(group,[]),grouped.get(group)!)).push(row);}return CompareResponse.parse({columns:cols.map(chip),groups:[...grouped].map(([group,rows])=>({group,label:group.replace(/_/g," "),rows})),as_of:s.asOf});}
function attributeGroup(predicate:string){if(["HAS_HEIGHT","HAS_MASS","HAS_PAYLOAD","HAS_DOF","HAS_REACH"].includes(predicate))return"PHYSICAL";if(["HAS_RUNTIME","SCORES_ON"].includes(predicate))return"PERFORMANCE";if(["HAS_LIST_PRICE","HAS_COMMERCIAL_STAGE"].includes(predicate))return"COMMERCIAL";return"IDENTITY";}

export async function atlasHandler(ctx:ApiContext,input:unknown){const q=AtlasQuery.parse(input),s=await load({...ctx,asOf:q.as_of??ctx.asOf});const pred={hq:"HQ_AT",rnd:"RND_AT",manufacturing:"MANUFACTURES_AT",deployments:"OCCURS_AT",research:"LOCATED_AT"}[q.layer]!;const bbox=q.bbox?.split(",").map(Number);const marks=new Map<string,{place:EntityRow;entities:EntityRow[]}>();for(const c of s.cs.filter(s.visible).filter(c=>c.predicate===pred&&c.objectEntityId)){const e=s.entity.get(c.subjectEntityId),p=s.entity.get(c.objectEntityId!);const d=p&&s.place.get(p.id);if(!e||!p||!d||d.lat===null||d.lng===null||(bbox&&(d.lng<bbox[0]!||d.lat<bbox[1]!||d.lng>bbox[2]!||d.lat>bbox[3]!)))continue;const m=marks.get(p.id)??(marks.set(p.id,{place:p,entities:[]}),marks.get(p.id)!);m.entities.push(e);}const payload=[...marks.values()].map(m=>{const d=s.place.get(m.place.id)!;const mix:Record<string,number>={};for(const e of m.entities)if(e.primaryEmbodiment)mix[e.primaryEmbodiment]=(mix[e.primaryEmbodiment]??0)+1;return{place:chip(m.place),lat:d.lat!,lng:d.lng!,country_code:m.place.countryCode,cluster_label:d.clusterLabel,entities:unique(m.entities.map(chip)),embodiment_mix:mix};});return AtlasResponse.parse({layer:q.layer,marks:payload,list:payload.flatMap(m=>m.entities.map(entity=>({entity,place:m.place}))),as_of:s.asOf});}

export async function updatesHandler(ctx:ApiContext,input:unknown){const q=UpdatesQuery.parse(input),s=await load(ctx);const events=s.events.filter(x=>(!q.since||x.observedAt>=`${q.since}T00:00:00.000Z`) && (!q.type||x.eventType===q.type)).flatMap(x=>{const entity=s.entity.get(x.entityId);if(!entity||q.embodiment&&entity.primaryEmbodiment!==q.embodiment)return[];const before=x.beforeClaimId?s.claim.get(x.beforeClaimId):null,after=x.afterClaimId?s.claim.get(x.afterClaimId):null;const c=after??before;return[{id:x.id,event_type:x.eventType,entity:chip(entity),before:before?value(s,before):null,after:after?value(s,after):null,evidence_summary:c?summary(s,c):null,observed_at:iso(x.observedAt)!,summary:x.summary}]}).sort((a,b)=>b.observed_at.localeCompare(a.observed_at)).slice(0,q.limit);return UpdatesResponse.parse({events});}

export async function claimEvidenceHandler(ctx:ApiContext,input:unknown){const p=ClaimEvidenceParams.parse((input as {params?:unknown})?.params??input),s=await load(ctx),c=s.claim.get(p.id);if(!c)throw new Error("claim not found");const subject=s.entity.get(c.subjectEntityId)!;const evs=s.evByClaim.get(c.id)??[];const corroboration=evs.length===0?"NOT_AVAILABLE":evs.some(e=>e.stance==="CONFLICTS")?"CONFLICTING":evs.length>1?"CORROBORATED":"SINGLE";const history=(s.bySubject.get(c.subjectEntityId)??[]).filter(x=>x.predicate===c.predicate&&x.stackLayer===c.stackLayer&&x.id!==c.id).sort((a,b)=>b.validFrom.localeCompare(a.validFrom)).map(x=>({claim_id:x.id,value:value(s,x),status:x.status,valid_from:x.validFrom,valid_to:x.validTo}));return ClaimEvidenceResponse.parse({claim:{claim_id:c.id,subject:chip(subject),predicate:c.predicate,label:predicateLabel(c.predicate),sentence:rowSentence(c,subject,c.objectEntityId?s.entity.get(c.objectEntityId):null),value:value(s,c),stack_layer:c.stackLayer,status:c.status,valid_from:c.validFrom,valid_to:c.validTo,observed_at:iso(c.observedAt)!,last_verified_at:iso(c.lastVerifiedAt)!},has_evidence:evs.length>0,corroboration,evidence:evs.map(e=>{const src=e.sourceId?s.source.get(e.sourceId):null;return{id:e.id,class:e.evidenceClass,confidence:e.confidence,stance:e.stance,excerpt:e.excerpt,published_at:iso(e.publishedAt),observed_at:iso(e.observedAt)!,source:src?{id:src.id,url:src.url,canonical_url:src.canonicalUrl,publisher:src.publisher,title:src.title,source_kind:src.sourceKind,published_at:iso(src.publishedAt),language:src.language}:null,assessment:assessmentView(s,e.id)}}),history,dependencies:(s.depByClaim.get(c.id)??[]).flatMap(id=>{const x=s.claim.get(id),e=x&&s.entity.get(x.subjectEntityId);return x&&e?[{claim_id:id,sentence:rowSentence(x,e,x.objectEntityId?s.entity.get(x.objectEntityId):null)}]:[]})});}

export async function projectGraph(ctx:ApiContext,input:{lens?:"embodiment"|"market"|"technology"|"geography"|"maturity";filter?:{entity_types?:string[];predicates?:string[];around?:string[]};as_of?:string}={}){const s=await load({...ctx,asOf:input.as_of??ctx.asOf});const filter=input.filter??{},around=new Set(filter.around??[]);const edgeRows=s.cs.filter(s.visible).filter(c=>c.objectEntityId).filter(c=>(!filter.predicates||filter.predicates.includes(c.predicate))).filter(c=>!around.size||around.has(s.entity.get(c.subjectEntityId)?.slug??"")||around.has(s.entity.get(c.objectEntityId!)?.slug??""));const ids=new Set(edgeRows.flatMap(c=>[c.subjectEntityId,c.objectEntityId!]));const nodes=[...ids].flatMap(id=>{const e=s.entity.get(id);return e&&(!filter.entity_types||filter.entity_types.includes(e.entityType))?[{id:e.id,chip:chip(e),group:e.primaryEmbodiment??null}]:[]});const allowed=new Set(nodes.map(n=>n.id));const edges=edgeRows.filter(c=>allowed.has(c.subjectEntityId)&&allowed.has(c.objectEntityId!)).map(c=>{const ev=s.evByClaim.get(c.id)??[];return{id:c.id,source:c.subjectEntityId,target:c.objectEntityId!,predicate:c.predicate,has_evidence:ev.length>0,confidence_max:maxConfidence(ev),valid_from:c.validFrom,valid_to:c.validTo,weight:ev.length?0.8:0.3};});return {lens:input.lens??"embodiment",nodes,edges,as_of:s.asOf};}
